/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RawgResultsDto } from './rawgResultsDto';


export interface RawgResponseDto { 
    count?: number;
    next?: string;
    previous?: string;
    results?: Array<RawgResultsDto>;
    seo_title?: string;
    seo_keywords?: string;
    seo_h1?: string;
    noindex?: boolean;
    nofollow?: boolean;
    description?: string;
    filters?: string;
    nofollow_collections?: string;
}

